### ISSUE TITLE
features request

### ISSUE THREAD

**Issue by Subramanian-MK** [lokendarjangid/waker_linux#4]
Notification before sleep: Some users may want to be notified before their computer goes to sleep, so they can save any unsaved work or cancel the sleep process if needed. Adding a notification feature could help prevent accidental loss of work or data.

Thank you 🥰..

**Comment by lokendarjangid** [comment]
do you want to work on this feature

**Comment by lokendarjangid** [comment]
you are assigned on this issue. make pull request when you finished on this issue
